### ISSUE TITLE
Pymon Refuses to Respond to Questions

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/pymon#24]
I'm going to dump the errors here:

```log
2022-12-29:14:21:05,763 ERROR    [client.py:1654] An exception has occurred while executing command `get`:
Traceback (most recent call last):
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord_slash\client.py", line 1353, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord_slash\model.py", line 210, in invoke
    return await self.func(*args, **kwargs)
  File "D:\Projects\cs-query-bot\pymon.py", line 132, in _get
    await ctx.send(embed=embed)
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord_slash\context.py", line 256, in send
    await self._http.post_initial_response(json_data, self.interaction_id, self._token)
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
```

**Comment by jrg94** [comment]
```
2022-12-29:14:21:27,729 ERROR    [client.py:1654] An exception has occurred while executing command `get`:
Traceback (most recent call last):
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord_slash\client.py", line 1353, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord_slash\model.py", line 210, in invoke
    return await self.func(*args, **kwargs)
  File "D:\Projects\cs-query-bot\pymon.py", line 132, in _get
    await ctx.send(embed=embed)
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord_slash\context.py", line 256, in send
    await self._http.post_initial_response(json_data, self.interaction_id, self._token)
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord\http.py", line 250, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

**Comment by jrg94** [comment]
Okay, found the actual bugs:

```
Traceback (most recent call last):
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "D:\Projects\cs-query-bot\pymon\bot.py", line 46, in on_message
    await self._react_on_mention(message)
  File "D:\Projects\cs-query-bot\pymon\bot.py", line 152, in _react_on_mention
    queries: list[models.Query] = self.brain.search(
  File "D:\Projects\cs-query-bot\pymon\brain.py", line 333, in search
    matches = cur.execute(command, (key_phrase, )).fetchall()
sqlite3.OperationalError: fts5: syntax error near "with"
```

**Comment by jrg94** [comment]
And another one:
```
Traceback (most recent call last):
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "D:\Projects\cs-query-bot\pymon\bot.py", line 77, in _get
    similar_queries = self.brain.search(query.query.removesuffix("?"))[1:4]
  File "D:\Projects\cs-query-bot\pymon\brain.py", line 333, in search
    matches = cur.execute(command, (key_phrase, )).fetchall()
sqlite3.OperationalError: no such column: ordered

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "D:\Projects\cs-query-bot\venv\lib\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'get' raised an exception: OperationalError: no such column: ordered
```
